"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "gruvbox_dark"

format = """
$os\
$username\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
$git_state\
[](fg:green bg:blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
[](fg:blue bg:bg3)\
$docker_context\
$conda\
$pixi\
$time\
$line_break\
$character
"""

[palettes.gruvbox_dark]
bg0 = "#282828"
bg1 = "#3c3836"
bg3 = "#665c54"
fg0 = "#fbf1c7"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
purple = "#b16286"
aqua = "#689d6a"
orange = "#d65d0e"

[os]
disabled = false
format = "[](fg:bg0 bg:red)[ $symbol ]($style)"
style = "bg:red fg:fg0 bold"

[os.symbols]
Arch = ""
Debian = ""
Fedora = ""
Linux = ""
Macos = ""
Mint = "󰣭"
Pop = ""
Ubuntu = ""
Windows = ""

[username]
show_always = true
format = "[](fg:red bg:orange)[ $user ]($style)"
style_user = "bg:orange fg:bg0"
style_root = "bg:orange fg:bg0"

[directory]
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾"
format = "[](fg:orange bg:yellow)[ $path$read_only ]($style)"
style = "bg:yellow fg:bg0"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""

[git_branch]
symbol = ""
format = "[](fg:green bg:green)[$symbol $branch]($style)"
style = "bg:green fg:bg0"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:green fg:bg0"

[git_state]
format = "[$state($progress_current/$progress_total)]($style)"
style = "bg:green fg:bg0"

[nodejs]
symbol = ""
format = "[ [$symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[bun]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[c]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[cpp]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[rust]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[golang]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[php]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[java]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[kotlin]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[haskell]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[python]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[ruby]
symbol = ""
format = "[[ $symbol( $version) ](fg:fg0 bg:blue)]($style)"
style = "bg:blue"

[docker_context]
symbol = ""
format = "[[ $symbol( $context) ](fg:#83a598 bg:bg3)]($style)"
style = "bg:bg3"

[conda]
format = "[[ $symbol( $environment) ](fg:#83a598 bg:bg3)]($style)"
style = "bg:bg3"

[pixi]
format = "[[ $symbol( $version)( $environment) ](fg:fg0 bg:bg3)]($style)"
style = "bg:bg3"

[time]
disabled = false
time_format = "%H:%M"
format = "[](fg:bg3 bg:bg1)[  $time ]($style)[](fg:bg1)"
style = "bg:bg1 fg:fg0"

[character]
success_symbol = "[](bold fg:green)"
error_symbol = "[](bold fg:red)"
vimcmd_symbol = "[](bold fg:green)"
vimcmd_replace_one_symbol = "[](bold fg:purple)"
vimcmd_replace_symbol = "[](bold fg:purple)"
vimcmd_visual_symbol = "[](bold fg:yellow)"
